import { lazy } from 'react'

export const Accordion = lazy(() => import('./accordion/Accordion'))
export const Button = lazy(() => import('./button/Button'))
export const Checkbox = lazy(() => import('./checkbox/Checkbox'))
export const Chip = lazy(() => import('./chip/Chip'))
export const DatePicker = lazy(() => import('./datepicker/DatePicker'))
export const Drawer = lazy(() => import('./drawer/Drawer'))
export const Modal = lazy(() => import('./modal/Modal'))
export const Select = lazy(() => import('./select/Select'))
export const Spinner = lazy(() => import('./spinner/Spinner'))
export const Switch = lazy(() => import('./switch/Switch'))
export const TextField = lazy(() => import('./textfield/TextField'))
export const TimePicker = lazy(() => import('./timepicker-new/TimePicker'))
export const UIProvider = lazy(() => import('./provider/UIProvider'))
